---
layout: cv
title: Sydney Winn's Resume
---
# Sydney Winn
Student, Future Business Owner.

## Currently

Student at Brigham Young University - Idaho

## Education

`2021-present`
__Brigham Young University Idaho.__

## Awards

`2020`
Kumon, *Outstanding Staff Award*, Solana Beach, CA 

## Skills
- Microsoft 360/Teams/Outlook
- SQL
- Python
- PowerBI


## Experience

`May 2024 - August 2024`
__Tuacahn Center for the Arts__, St George Utah
*Marketing Intern* 
- Assisted in creating engaging content for social media platforms to enhance online presence
- Contributed to the development of marketing materials - including copywriting, graphic design, and multimedia content creation
- Supported the marketing team in promoting and working events
- Collaborated with cross-functional teams to ensure cohesive and effective marketing campaigns

`June 2023 - September 2023`
__Dexcom__, Carlsbad California
*Administrative Assistant 1, Human Resources*
- Redesigned onboarding and new-hire meetings
- Reorganized Human Resources documents for easier access
- Coordinated “360 Reviews” on Qualtrics and BetterUp
- Prepared “DE&I at Dexcom” new-hire video
- Planned and organized materials for VP 2023 event 

`July 2021 - September 2021`
__Warner Pediatric Dental__, Encinitas California
*Sterilizer/Dental Assistant*
- Sterilized and cleaned dental instruments and offices
- Supplied  dental-hygienists by providing tools and equipment
- Helped with administrative tasks

`September 2019 - September 2021`
__Kumon__, Solana Beach California
*Tutor/Grader*
- Tutored children of all ages math and reading
- Prepared student’s classwork and homework
- Emailed and communicated with clients 
- Prepared monthly and recurring payments